#!/bin/bash
#
# kasutaja lisamine genereeritud parooliga
# autor Raigo Hoim
if [ $# -ne 1 ]; then
    echo "Kasutusjuhend: $0 failinimi"
else
  failinimi=$1
  if [ -f $failinimi -a -r $failinimi ]; then
    echo "fail on olemas!"
    for rida in $(paste -d: $failinimi $paroolid)
    do
	kasutajanimi=$(echo "$rida" | cut -f1 -d:)
	sh lisa_kasutaja $kasutajanimi
	# genereerimise käsk
	parool=$(pwgen -s 8 1)
	echo "$kasutajanimi:$parool" | chpasswd
	echo "$kasutajanimi - $parool" >> loodud_kasutajad_paroolidega
    done
  else
    echo "Probleem failiga $failinimi"
  fi
fi
